---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-management-app
  namespace: default
  labels:
    app: payment-management-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-management-app
  template:
    metadata:
      labels:
        app: payment-management-app
    spec:
      containers:
      - name: payment-management-app
        image: "devopshint/payment-managementapp-1.0:latest"
        ports:
          - containerPort: 8003


---
apiVersion: v1
kind: Service
metadata:
  name: payment-management-app
  namespace: default
spec:
  selector:
    app: payment-management-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8003
    port: 8003